#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

module load eb
module load Miniconda2
module load R


source deactivate

source activate qiime1

export TMPDIR=~/qiime_tmp

R --no-save


compare_categories.py --method anosim -i ~/results/cut_cdout/bdiv_even30000/unweighted_unifrac_dm.txt -m ~/analysis/cut_map -c SampleNitrogen -o ~/results/cut_anosim_out_N_2 -n 999 



source deactivate
 
