#!/bin/bash
#SBATCH -t 1:00:00
#SBATCH -n 24
#SBATCH -p short

module load eb
module load Miniconda2 

source deactivate

source activate qiime1

export TMPDIR=~/qiime_tmp 

#Summarizing OTU table using Sample Nitrogen
summarize_taxa_through_plots.py \
-i analysis/cut_otu_table_bac/otu_table_D_0__Bacteria.biom \
-o ~/results/97_taxa_N \
-m ~/analysis/cut_map \
-c SampleNitrogen \

source deactivate
